#!/bin/bash
#_NORC=1
if [ -e "$HOME/.bash_profile" ]; then
	echo 'calling .bash_profile'
	. $HOME/.bash_profile
	echo '.bash_profile DONE'
else
	echo 'calling .profile'
	. $HOME/.profile
	echo '.profile DONE'
fi
if ! which randomBackground; then
	echo 'NO PATH?!?!' "(PATH=$PATH)"
	. $HOME/.bashrc
fi

if [ -x ~/bin/screens.sh ]; then
	~/bin/screens.sh
fi

if which xset >/dev/null 2>&1; then
	# disable bell
	xset -b
fi
~/bin/xkbmap
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

# exec startlxde
# exec dbus-launch lxsession -a
for nm in urxvtcd sakura lxterminal xfce4-terminal; do
    if which $nm >/dev/null 2>/dev/null; then
        export TERMINAL=$nm
        break
    fi
done

if which xrdb && [ -f ~/.Xresources ]; then
    xrdb -merge ~/.Xresources
fi

for nm in fbxkb gxkb; do
	if which $nm; then
		$nm &
		break
	fi
done
if which nm-applet >/dev/null 2>&1; then
    nm-applet &
fi
if which dropbox >/dev/null 2>&1; then
	(sleep 5; dropbox start) &
fi
if which pulseaudio; then
	pulseaudio --daemonize &
fi
#if which groximity 2>/dev/null; then
#    groximity 20:13:E0:36:E7:53 &
#else
    if which xscreensaver 2>/dev/null; then
        xscreensaver &
    fi
#fi
(
if [ -d ~/.screenlayout ]; then
    sleep 0.5
    if xrandr -q | grep -q 'HDMI1 connected'; then
        ~/.screenlayout/unosoft.sh &
    else
        if [ -x ~/.screenlayout/solitaire.sh ]; then
            ~/.screenlayout/solitaire.sh &
        fi
    fi
    sleep 1
fi
) &

if [ -x ~/bin/nasaBackground ]; then
    (
    sleep 3
    ~/bin/nasaBackground
    ) &
fi
if which autocutsel >/dev/null; then
	autocutsel -s PRIMARY -fork
fi

if which redshift >/dev/null; then
    redshift -l 17.498333:19.040833 -t 6500:3600 -l manual &
elif [ -x $HOME/bin/xflux ] && ! pidof xflux >/dev/null; then
    $HOME/bin/xflux -l 47.498333 -g 19.040833
fi

if synclient -l | grep -q 'RightEdge.*= 1175$'; then
	synclient ClickPad=1 BottomEdge=600
fi

if [ -x /usr/bin/mate-power-manager ]; then
	/usr/bin/mate-power-manager &
fi

if [ -x /usr/bin/xinput ] && [ $(hostname) = redpath ]; then
	xinput --set-prop 12 275 1
fi

#if [ -x /usr/bin/xfsettingsd ]; then
	#{ sleep 2; xfsettingsd; } &
#fi
if which ck-launch-session 2>/dev/null; then
	exec ck-launch-session dbus-launch i3
fi
exec i3
