#!/bin/bash
#_NORC=1
if [ -e "$HOME/.bash_profile" ]; then
	echo 'calling .bash_profile'
	. $HOME/.bash_profile
	echo '.bash_profile DONE'
else
	echo 'calling .profile'
	. $HOME/.profile
	echo '.profile DONE'
fi
if ! which randomBackground; then
	echo 'NO PATH?!?!' "(PATH=$PATH)"
	. $HOME/.bashrc
fi

if [ -x ~/bin/screens.sh ]; then
	~/bin/screens.sh
fi

# exec startlxde
# exec dbus-launch lxsession -a
for nm in urxvtcd sakura lxterminal xfce4-terminal; do
    if which $nm >/dev/null 2>/dev/null; then
        export TERMINAL=$nm
        break
    fi
done

xset b off
~/bin/xkbmap
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

if [ -f ~/.Xresources ]; then
    xrdb -merge ~/.Xresources
fi

fbxkb &
if which nm-applet >/dev/null 2>&1; then
    nm-applet &
else
    connman-ui-gtk &
fi
if which dropbox >/dev/null 2>&1; then
	(sleep 5; dropbox start) &
fi
pulseaudio --daemonize &
#if which groximity 2>/dev/null; then
#    groximity 20:13:E0:36:E7:53 &
#else
    if which xscreensaver 2>/dev/null; then
        xscreensaver &
    fi
#fi
#exec ck-launch-session dbus-launch awesome
(
if [ -d ~/.screenlayout ]; then
    sleep 0.5
    if xrandr -q | grep -q 'HDMI1 connected'; then
        ~/.screenlayout/unosoft.sh &
    else
        if [ -x ~/.screenlayout/solitaire.sh ]; then
            ~/.screenlayout/solitaire.sh &
        fi
    fi
    sleep 1
fi
) &

(
for i in seq 120; do
	if ip route | fgrep 10.65.25.0; then
        p520.mountall
		break
    else
	    sleep 2
    fi
done
) &

if [ -x /usr/bin/emacs ]; then
	emacs --daemon &
fi

if [ -x ~/bin/nasaBackground.sh ]; then
    (
    sleep 3
    ~/bin/nasaBackground.sh
    ) &
fi
which autocutsel >/dev/null && autocutsel -s PRIMARY -fork

if [ -x /usr/bin/parcellite ]; then
	parcellite &
fi

if which redshift >/dev/null; then
    redshift -l 17.498333:19.040833 -t 6500:3600 -l manual &
elif [ -x $HOME/bin/xflux ] && ! pidof xflux >/dev/null; then
    $HOME/bin/xflux -l 47.498333 -g 19.040833
fi

if synclient -l | grep -q 'RightEdge.*= 1175$'; then
	synclient ClickPad=1 BottomEdge=600
fi

if [ -x /usr/bin/xfsettingsd ]; then
	{ sleep 2; xfsettingsd; } &
fi
if which ck-launch-session 2>/dev/null; then
	exec ck-launch-session dbus-launch i3
fi
exec i3

