#!/bin/sh
if [ -x /usr/bin/ntpdate ]; then
	exec ntpdate -sB hu.pool.ntp.org europe.pool.ntp.org pool.ntp.org
fi
password=$(cat /etc/chrony/chrony.keys | head -n1 | awk '{print $2}')
chronyc >/dev/null <<EOF
password ${password}
burst 3/6
sourcestats
makestep
EOF
