#!/bin/sh
set -e

# Tarsnap backup script
# Written by Tim Bishop, 2009.

# Directories to backup
DIRS="/root/tarsnap-dirs"

# Number of daily backups to keep
DAILY=7

# Number of weekly backups to keep
WEEKLY=4
# Which day to do weekly backups on
# 1-7, Monday = 1
WEEKLY_DAY=1

# Number of monthly backups to keep
MONTHLY=3
# Which day to do monthly backups on
# 01-31 (leading 0 is important)
MONTHLY_DAY=01

# Path to tarsnap
#TARSNAP="/home/tdb/tarsnap/tarsnap.pl"
TSNAP=/usr/bin/tarsnap
if [ -x /usr/local/sbin/tsnap ]; then
	TSNAP=/usr/local/sbin/tsnap
fi
TARSNAP="nice -n15 ionice -c3 $TSNAP"

# end of config

# day of week: 1-7, monday = 1
DOW=`date +%u`
# day of month: 01-31
DOM=`date +%d`
# month of year: 01-12
MOY=`date +%m`
# year
YEAR=`date +%Y`
# time
TIME=`date +%H%M%S`

# Backup name
if [ X"$DOM" = X"$MONTHLY_DAY" ]; then
	# monthly backup
	BACKUP="$YEAR$MOY$DOM-$TIME-monthly"
elif [ X"$DOW" = X"$WEEKLY_DAY" ]; then
	# weekly backup
	BACKUP="$YEAR$MOY$DOM-$TIME-weekly"
else
	# daily backup
	BACKUP="$YEAR$MOY$DOM-$TIME-daily"
fi

$TARSNAP --fsck

# Do backups
cat $DIRS | while read dir; do
	EXTRA_FLAGS=
	base=$dir
	if echo "$dir" | grep -q ' '; then
		base=${dir%% *}
		dir=${dir#* }
		EXTRA_FLAGS="-C $base"
	fi

	echo "==> create $BACKUP-$base-$dir"
	echo $TARSNAP $EXTRA_FLAGS --one-file-system -c -f $BACKUP-$base $dir
	$TARSNAP $EXTRA_FLAGS --one-file-system -c -f $BACKUP-$base $dir
done

$TARSNAP --print-stats
# Backups done, time for cleaning up old archives

# using tail to find archives to delete, but its
# +n syntax is out by one from what we want to do
# (also +0 == +1, so we're safe :-)
DAILY=`expr $DAILY + 1`
WEEKLY=`expr $WEEKLY + 1`
MONTHLY=`expr $MONTHLY + 1`

# Do deletes
TMPFILE=/tmp/tarsnap.archives.$$
$TARSNAP --list-archives > $TMPFILE
if [ $? != 0 ]; then
	echo "Error found while listing tarsnap archives! Old archives will not be cleared this time."
	rm $TMPFILE
	break
else
	# for dir in $DIRS; do
	cat $TMPFILE | cut -d- -f4- | sort | uniq | while read dir; do
		for params in "daily $DAILY" "weekly $WEEKLY" "monthly $MONTHLY"; do
			txt=${params%% *}
			num=${params#* }
			for i in $(grep -E "^[[:digit:]]{8}-[[:digit:]]{6}-$txt-$dir" $TMPFILE | sort -rn \
					| tail -n +$num); do
				echo "==> delete $i"
				$TARSNAP -d -f $i
			done
		done
	done
fi
rm $TMPFILE

$TARSNAP --print-stats
