theme = "solarized_light"

[editor]
cursorline = true
bufferline = "multiple"

[editor.whitespace.render]
tab = "all"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.soft-wrap]
enable = true

