#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vi'
export VISUAL='view'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Temporary Files
#

if [[ -z "$TMPDIR" ]]; then
    export TMPDIR=/tmp
fi

if [[ -d "$TMPDIR" ]]; then
  export TMPPREFIX="${TMPDIR%/}/zsh"
  if [[ ! -d "$TMPPREFIX" ]]; then
    mkdir -p "$TMPPREFIX"
  fi
fi


# PATH
export CHROMIUM_USER_FLAGS="--memory-model=low --purge-memory-button --enable-internal-flash"
if [[ -d $HOME/bin ]]; then
    export PATH=$HOME/bin:$PATH
fi

GOPATH=~/projects/go
if [[ -d "$GOPATH" ]]; then
    export GOPATH
    if [[ -x /usr/local/go/bin/go ]]; then
        export GOROOT=/usr/local/go
        export PATH=$PATH:$GOPATH/bin:$GOROOT/bin
    fi
fi

ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
if [ -d $ORACLE_HOME ]; then
    export ORACLE_HOME
    export ORACLE_SID=XE
    export ORACLE_BASE=/u01/app/oracle
    export PATH=$ORACLE_HOME/bin:$PATH
fi

for nm in sakura lxterminal xfce4-terminal urxvtcd; do
    if which $nm >/dev/null; then
        export TERMINAL=$nm
        break
    fi
done

gpg_agent_info=/tmp/$USER/.gpg-agent-info
if [ -d /tmp/$USER ]; then
    if [ -f "$gpg_agent_info" ]; then
        . "$gpg_agent_info"
        if [ $(readlink /proc/$SSH_AGENT_PID/exe) = '/usr/bin/gpg-agent' ]; then
            #echo "$gpg_agent_info OK"
            . "$gpg_agent_info"
            export GPG_AGENT_INFO
            export SSH_AUTH_SOCK
            export SSH_AGENT_PID
        else
            echo "stale $gpg_agent_info"
            rm $gpg_agent_info
        fi
    fi
else
    mkdir -p /tmp/$USER
fi
if [ ! -f "$gpg_agent_info" ]; then
    echo "starting new gpg-agent"
    eval $(gpg-agent --daemon --enable-ssh-support \
        --write-env-file "$gpg_agent_info")
fi
if ssh-add -l | grep -q tgulacsi@unosoft; then
else
    ssh-add ~/.ssh/id_rsa
    ssh-add tgulacsi@unosoft
fi

# TERM
export TERM='xterm-256color'
