#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -z "$ZDOTDIR" ]]; then
    export ZDOTDIR=$HOME
fi
source "$ZDOTDIR/.zprezto/init.zsh"

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory extendedglob nomatch notify clobber
unsetopt autocd
alias rm='nocorrect rm'
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/gthomas/.zshrc'

autoload -Uz compinit && compinit
# End of lines added by compinstall

#colors and prompt
autoload -U colors && colors
#PS1="%{$fg[red]%}%n%{$reset_color%}@%{$fg[blue]%}%m %{$fg[yellow]%}%~ %{$reset_color%}%% "

#aliases
alias l='ls -lA --color=auto'
alias go-windows-386='CGO_ENABLED=1 GOOS=windows GOARCH=386 go "$@"'
#alias go-linux-386='CGO_ENABLED=1 GOOS=linux GOARCH=386 go "$@"'
#export EDITOR='emacsclient -t'
#alias vi='emacsclient --alternate-editor= -t '


ulimit -v 2048000 -m 2048000 -d 2048000

function makelink {
    DN=$1
    if readlink ~/$DN >/dev/null; then
        mkdir -p $(readlink ~/$DN)
    else
        D=/tmp/${USER}
        if [ -d $D/$DN ]; then
            echo "Deleting ~/$DN"
            rm -rf ~/$DN && ln -fs $D/$DN ~/$DN
        else
            echo "Deleting $D/$DN"
            rm -rf $D/$DN
            echo "Moving ~/$DN to $D/$DN"
            mkdir -p $D && mv ~/$DN $D/ && ln -fs $D/$DN ~/$DN
        fi
    fi
}

makelink .cache
makelink Downloads

(cd $HOME
for nm in .mozilla/firefox/*/Cache; do
    if readlink $nm >/dev/null; then
    else
        mkdir -p .cache/mozilla/firefox
        LN=$HOME/.cache/mozilla/firefox/$(dirname $nm)
        echo "Moving $nm to $LN"
        mv $nm $LN
        rm -rf $nm
        ln -fs $LN $nm
    fi
done)

[ -x ~/bin/uno-ssh ] && . ~/bin/uno-ssh
# tmux
if which tmux 2>&1 >/dev/null; then
    if [ -z "$TMUX" ] && [ "$TERM" = urxvt-unicode ]; then
        exec tmux
    fi
fi
