#!/bin/sh -e
USER=consul
HOME=/var/lib/$USER
if ! fgrep -q $USER /etc/passwd; then
	useradd -d $HOME -m -r -N $USER
fi
if [ ! -e /etc/${USER}.d ]; then
	mkdir -p /etc/${USER}.d
fi
if [ ! -e $HOME ]; then
    mkdir -p $HOME
    chown $USER $HOME
fi

if ! ping -W 1 -c 1 10.65.25.1 >/dev/null; then
	echo '10.65.25.1 is not reachable' >&2
	sleep 30
	exit 0
fi

addr=$(ip addr | sed -nE '/inet/ s/^.*inet ([1-9][0-9.]*).*(usb|eth|wlan)[0-9]$/\1/p')
if [ -z "$addr" ]; then
	echo 'no addr present' >&2
	sleep 30
	exit 0
fi
srv=10.65.25.42
dc=unosoft
if [ "$(expr substr "$addr" 1 3)" = '192' ]; then
	srv=10.65.25.42
	dc=unosoft-subsid
else
	srv=10.65.25.28
	dc=unosoft-inner
fi

set -x
exec chpst -u $USER /usr/local/bin/consul agent \
	-ui-dir=/usr/local/share/consul/dist \
	-retry-join=$srv \
	-dc=$dc \
    -config-dir=/etc/${USER}.d \
    -data-dir=$HOME
