#!/bin/sh
alias apu='TERM=xterm sudo nice -n5 ionice -c2 -n5 aptitude -u'
VIM=$(which vim) && alias vi='env -u TMUX vim'
alias ls='ls --color=auto'
alias l='ls -lA --color=auto'
alias A='sudo aptitude -o "Acquire::http::Proxy=;"'
alias update='sudo -- sh -c "apt update && apt -y upgrade && apt -y --purge autoremove && apt -y clean"'
alias pass='gopass'
