#!/bin/bash
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# set PATH so it includes user's private bin if it exists
#export LANGUAGE="hu_HU:en_US:en"
export LANGUAGE="en"
export LANG="hu_HU.UTF-8"
export LC_ALL=
#export ENV=$HOME/.profile

export TMPDIR=${TMPDIR:-/tmp}
if [ -x /usr/bin/emacsclient ]; then
	EDITOR='emacsclient -nw'
else
	EDITOR='vim'
fi
export EDITOR
export VISUAL=$EDITOR
export PAGER='less'

eval $($HOME/bin/invoke-gpg-agent)

if [[ -z "$SUDO_ASKPASS" ]]; then
    export SUDO_ASKPASS=/usr/bin/ssh-askpass
fi

if [[ -d /usr/local/plan9 ]]; then
    export PLAN9=/usr/local/plan9
    PATH=$PATH:$PLAN9/bin
fi

if [[ -z "$GOPATH" ]]; then
    GOPATH=$HOME
	export GO15VENDOREXPERIMENT=1
	export GOVC_INSECURE=1 GOVC_URL=vcenterappl.unosoft.local
	export GOVC_USERNAME=TGulacsi@unosoft
    if [[ -d "$GOPATH" ]]; then
        export GOPATH
        if [[ -x /usr/local/go/bin/go ]]; then
            #export GOROOT=/usr/local/go
            PATH=/usr/local/go/bin:$PATH
        fi
        if [[ $GOPATH != $HOME ]]; then
            PATH=$PATH:$GOPATH/bin
        fi
    fi
	if [[ -z "$GOROOT_BOOTSTRAP" ]] && [[ -e /usr/local/go1.4.2/bin/go ]]; then
		export GOROOT_BOOTSTRAP=/usr/local/go1.4.2
	fi
fi
if [[ -z "_OHOME_HAS_BEEN_SET" ]]; then
	export TNS_ADMIN=$HOME
    #echo OH=$ORACLE_HOME
    if [[ -z "$ORACLE_HOME" ]]; then
        for bdn in /u01/app/oracle/product /usr/lib/oracle; do
            #echo "bdn=$bdn"
            if [[ ! -d $bdn ]]; then
                continue
            fi
            find "$bdn" -maxdepth 2 -type d \( -name xe -o -name client64 \) \
                    2>/dev/null | head -n1 | while read dn; do
                #echo "#dn=$dn"
                export ORACLE_BASE=$bdn
                export ORACLE_HOME=$dn
                #export ORACLE_SID=XE
                export PATH=$ORACLE_HOME/bin:$PATH
                #echo "H=$ORACLE_HOME"
                break
            done
            break
        done
    fi
    #echo OH=$ORACLE_HOME
    _OHOME_HAS_BEEN_SET=1
fi


if [[ -z "$_PATH_HAS_BEEN_SET" ]]; then
    export CDPATH=.:~:$GOPATH/src/github.com/tgulacsi

    if [[ -d "$HOME/bin" ]] && echo "$PATH" | grep -vq $HOME/bin; then
        PATH="$HOME/bin:$PATH"
    fi
	export PATH
    _PATH_HAS_BEEN_SET=1
fi

if [[ -z $ORA_CGO_CFLAGS ]]; then
	fn=$GOPATH/src/gopkg.in/goracle.v1/env
	if [[ -x $fn ]]; then
		. $fn
		export ORA_CGO_CFLAGS=$CGO_CFLAGS
		export ORA_CGO_LDFLAGS=$CGO_LDFLAGS
		unset CGO_CFLAGS
		unset CGO_LDFLAGS
	fi
fi

alias travis='docker run --rm -v $PWD:/repo -v ~/.travis:/travis andredumas/travis-ci-cli'
alias l='ls -lA --color=auto'

export PS1="\[\e[1;32m\]\u@\H:\[\e[m\] \[\e[1;37m\]\w\[\e[m\]\n\`if [ \$? = 0 ]; then echo \[\e[33m\]^_^\[\e[0m\]; else echo \[\e[31m\]O_O\[\e[0m\]; fi\` \\$ "
